import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import KioskShell from '../../components/KioskShell';
import { useApp } from '../../context/AppContext';
import { updateQueueToken } from '../../data/queueStore';
import { VoiceBar, StatusTag, speakText } from '../../components/ui';

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${GEMINI_API_KEY}`;

export default function AiAssistant() {
  const { state, patch } = useApp();
  const nav = useNavigate();
  
  const lang = state.language || 'English';
  
  const SYSTEM_INSTRUCTION = `You are an AI Clinical Intake Assistant for AAROGYAVAANI. 
Your goal is to gather the patient's Chief Complaint, Symptoms, and relevant medical history in a friendly, concise manner.
Ask 1 or 2 questions at most at a time.
IMPORTANT: You MUST communicate with the patient entirely in ${lang}.
If the patient provides an image or report, acknowledge it and factor it into the assessment.
Keep your responses short.
When you have successfully gathered enough information (Chief complaint, main symptoms, and duration), you MUST end your message with the exact tag: [ASSESSMENT_COMPLETE]
Then, in a new line, provide a brief JSON summary block wrapped in \`\`\`json { "chiefComplaint": "...", "department": "General Medicine", "priority": "P3" } \`\`\`
Make sure the JSON block is the very last thing.`;

  const getInitialMessage = () => {
    const name = state.patient?.name?.split(' ')[0] || '';
    if (lang === 'हिन्दी') {
      return `नमस्ते ${name}, मैं आपका AI क्लिनिकल असिस्टेंट हूँ। क्या आप संक्षेप में बता सकते हैं कि आज आप अस्पताल क्यों आए हैं?`;
    }
    if (lang === 'ਪੰਜਾਬੀ') {
      return `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ${name}, ਮੈਂ ਤੁਹਾਡਾ AI ਕਲੀਨਿਕਲ ਸਹਾਇਕ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਸੰਖੇਪ ਵਿੱਚ ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਅੱਜ ਹਸਪਤਾਲ ਕਿਉਂ ਆਏ ਹੋ?`;
    }
    return `Hello ${name}, I am your AI clinical assistant. Could you briefly describe what brings you to the hospital today?`;
  };

  const getVoiceBarText = () => {
    if (lang === 'हिन्दी') {
      return assessmentDone ? "कृपया अपने मूल्यांकन सारांश की पुष्टि करें।" : "मैं सुन रहा हूँ। कृपया अपनी स्वास्थ्य संबंधी चिंताओं का वर्णन करें।";
    }
    if (lang === 'ਪੰਜਾਬੀ') {
      return assessmentDone ? "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਮੁਲਾਂਕਣ ਸੰਖੇਪ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।" : "ਮੈਂ ਸੁਣ ਰਿਹਾ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀਆਂ ਸਿਹਤ ਸਮੱਸਿਆਵਾਂ ਦਾ ਵਰਣਨ ਕਰੋ।";
    }
    return assessmentDone ? "Please verify your assessment summary." : "I am listening. Please describe your health concerns.";
  };

  const getTranslated = (key) => {
    const d = {
      stepLabel: { English: 'STEP 2 · AI TRIAGE', 'हिन्दी': 'चरण 2 · AI ट्राइएज', 'ਪੰਜਾਬੀ': 'ਕਦਮ 2 · AI ਟ੍ਰਾਈਏਜ' },
      title: { English: 'AI Clinical Assistant', 'हिन्दी': 'AI क्लिनिकल असिस्टेंट', 'ਪੰਜਾਬੀ': 'AI ਕਲੀਨਿਕਲ ਸਹਾਇਕ' },
      typing: { English: 'AI is typing...', 'हिन्दी': 'AI टाइप कर रहा है...', 'ਪੰਜਾਬੀ': 'AI ਟਾਈਪ ਕਰ ਰਿਹਾ ਹੈ...' },
      attach: { English: '📎 Attach', 'हिन्दी': '📎 फाइल जोड़ें', 'ਪੰਜਾਬੀ': '📎 ਫਾਈਲ ਜੋੜੋ' },
      speak: { English: '🎤 Speak', 'हिन्दी': '🎤 बोलें', 'ਪੰਜਾਬੀ': '🎤 ਬੋਲੋ' },
      listening: { English: '🎙️ Listening...', 'हिन्दी': '🎙️ सुन रहा हूँ...', 'ਪੰਜਾਬੀ': '🎙️ ਸੁਣ ਰਿਹਾ ਹਾਂ...' },
      placeholder: { English: 'Type your symptoms here...', 'हिन्दी': 'अपने लक्षण यहाँ टाइप करें...', 'ਪੰਜਾਬੀ': 'ਆਪਣੇ ਲੱਛਣ ਇੱਥੇ ਟਾਈਪ ਕਰੋ...' },
      send: { English: 'Send', 'हिन्दी': 'भेजें', 'ਪੰਜਾਬੀ': 'ਭੇਜੋ' },
      complete: { English: 'Assessment Complete', 'हिन्दी': 'मूल्यांकन पूरा हुआ', 'ਪੰਜਾਬੀ': 'ਮੁਲਾਂਕਣ ਪੂਰਾ ਹੋਇਆ' },
      verify: { English: 'Please verify the summary generated by the AI before we issue your token.', 'हिन्दी': 'टोकन जारी करने से पहले कृपया AI द्वारा बनाए गए सारांश की पुष्टि करें।', 'ਪੰਜਾਬੀ': 'ਟੋਕਨ ਜਾਰੀ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਕਿਰਪਾ ਕਰਕੇ AI ਦੁਆਰਾ ਬਣਾਏ ਗਏ ਸੰਖੇਪ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।' },
      dept: { English: 'Suggested Department', 'हिन्दी': 'सुझाया गया विभाग', 'ਪੰਜਾਬੀ': 'ਸੁਝਾਇਆ ਗਿਆ ਵਿਭਾਗ' },
      chief: { English: 'Chief Complaint', 'हिन्दी': 'मुख्य शिकायत', 'ਪੰਜਾਬੀ': 'ਮੁੱਖ ਸ਼ਿਕਾਇਤ' },
      priority: { English: 'Priority Assessment', 'हिन्दी': 'प्राथमिकता मूल्यांकन', 'ਪੰਜਾਬੀ': 'ਤਰਜੀਹ ਮੁਲਾਂਕਣ' },
      modify: { English: 'Modify Details', 'हिन्दी': 'विवरण बदलें', 'ਪੰਜਾਬੀ': 'ਵੇਰਵੇ ਬਦਲੋ' },
      confirm: { English: 'Confirm & Send to Doctor', 'हिन्दी': 'पुष्टि करें और डॉक्टर को भेजें', 'ਪੰਜਾਬੀ': 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਡਾਕਟਰ ਨੂੰ ਭੇਜੋ' },
      error: { English: 'Sorry, I encountered an error.', 'हिन्दी': 'क्षमा करें, मुझे एक त्रुटि मिली।', 'ਪੰਜਾਬੀ': 'ਮਾਫ ਕਰਨਾ, ਮੈਨੂੰ ਇੱਕ ਗਲਤੀ ਆਈ।' }
    };
    return d[key][state.language] || d[key]['English'];
  };

  const [messages, setMessages] = useState([
    { role: 'model', text: getInitialMessage() }
  ]);
  const [input, setInput] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [loading, setLoading] = useState(false);
  const [assessmentDone, setAssessmentDone] = useState(false);
  const [summaryData, setSummaryData] = useState(null);
  
  const chatEndRef = useRef(null);

  // Auto-speak initial message once on mount
  useEffect(() => {
    let langCode = 'en-US';
    if (lang === 'हिन्दी') langCode = 'hi-IN';
    else if (lang === 'ਪੰਜਾਬੀ') langCode = 'pa-IN';
    speakText(getInitialMessage(), langCode);
  }, []);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const toggleListen = () => {
    if (isListening) return; // Speech recognition will auto-stop
    
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Voice recognition is not supported in this browser.");
      return;
    }
    const recognition = new SpeechRecognition();
    if (lang === 'हिन्दी') recognition.lang = 'hi-IN';
    else if (lang === 'ਪੰਜਾਬੀ') recognition.lang = 'pa-IN';
    else recognition.lang = 'en-US';
    recognition.interimResults = false;
    
    recognition.onstart = () => setIsListening(true);
    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;
      setInput(prev => prev + ' ' + transcript);
    };
    recognition.onerror = (event) => {
      console.error(event.error);
      setIsListening(false);
    };
    recognition.onend = () => setIsListening(false);
    
    recognition.start();
  };

  const handleSend = async (imageFile = null) => {
    if (!input.trim() && !imageFile) return;
    
    const userText = input.trim();
    setInput('');
    
    const newMsg = { role: 'user', text: userText };
    let inlineData = null;
    
    if (imageFile) {
      newMsg.imageName = imageFile.name;
      const reader = new FileReader();
      const base64Promise = new Promise((resolve) => {
        reader.onload = (e) => {
          const b64 = e.target.result.split(',')[1];
          resolve({ mimeType: imageFile.type, data: b64 });
        };
      });
      reader.readAsDataURL(imageFile);
      inlineData = await base64Promise;
      newMsg.text = newMsg.text || 'Uploaded a file.';
    }
    
    const updatedMessages = [...messages, newMsg];
    setMessages(updatedMessages);
    setLoading(true);

    try {
      const rawContents = updatedMessages
        .filter((m, i) => !(i === 0 && m.role === 'model'))
        .filter(m => !m.text.includes('Network error') && !m.text.includes('त्रुटि') && !m.text.includes('ਗਲਤੀ'))
        .map(m => {
          const parts = [{ text: m.text }];
          if (m.role === 'user' && inlineData && m === newMsg) {
            parts.push({ inlineData });
          }
          return { role: m.role === 'model' ? 'model' : 'user', parts };
        });

      const contents = [];
      for (const msg of rawContents) {
        if (contents.length > 0 && contents[contents.length - 1].role === msg.role) {
          contents[contents.length - 1].parts.push({ text: '\n\n' }, ...msg.parts);
        } else {
          contents.push(msg);
        }
      }

      const response = await fetch(GEMINI_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: SYSTEM_INSTRUCTION }] },
          contents
        })
      });

      const data = await response.json();
      if (!response.ok) {
        console.error("Gemini API Error:", data);
        throw new Error(data.error?.message || 'API Error');
      }

      const botText = data.candidates?.[0]?.content?.parts?.[0]?.text || getTranslated('error');
      
      let cleanText = botText;
      if (botText.includes('[ASSESSMENT_COMPLETE]')) {
        cleanText = botText.split('[ASSESSMENT_COMPLETE]')[0].trim();
        const jsonMatch = botText.match(/```json([\s\S]*?)```/);
        if (jsonMatch) {
          try {
            const parsed = JSON.parse(jsonMatch[1]);
            setSummaryData(parsed);
          } catch (e) {
            setSummaryData({ chiefComplaint: 'Needs review', department: 'General Medicine', priority: 'P3' });
          }
        }
        setAssessmentDone(true);
      }

      setMessages(prev => [...prev, { role: 'model', text: cleanText }]);
      
      // Auto-speak the AI's response
      let langCode = 'en-US';
      if (lang === 'हिन्दी') langCode = 'hi-IN';
      else if (lang === 'ਪੰਜਾਬੀ') langCode = 'pa-IN';
      speakText(cleanText, langCode);
      
    } catch (error) {
      console.error(error);
      setMessages(prev => [...prev, { role: 'model', text: getTranslated('error') }]);
    } finally {
      setLoading(false);
    }
  };

  const onFileChange = (e) => {
    const file = e.target.files[0];
    if (file) handleSend(file);
    e.target.value = null;
  };

  const confirmAndProceed = () => {
    if (summaryData) {
      const { chiefComplaint, department, priority } = summaryData;
      patch({
        department: { name: department || 'General Medicine' },
        chiefComplaint: chiefComplaint || 'Details gathered via AI',
      });
      
      const tokenNo = state.token?.tokenNo;
      if (tokenNo) {
        updateQueueToken(tokenNo, {
          department: department || 'General Medicine',
          chiefComplaint: chiefComplaint || 'Details gathered via AI',
          priority: priority || 'P3'
        });
      }
    }
    nav('/checkin/token');
  };

  return (
    <KioskShell stepLabel={getTranslated('stepLabel')} title={getTranslated('title')} back="/checkin/confirm" progress={55} hideNav isListening={isListening}>
      <VoiceBar text={getVoiceBarText()} />
      
      {!assessmentDone ? (
        <div style={{ display: 'flex', flexDirection: 'column', height: '55vh' }}>
          <div style={{ flex: 1, overflowY: 'auto', padding: '16px', background: '#F8FAFC', borderRadius: '8px', marginBottom: '16px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {messages.map((msg, i) => (
              <div key={i} style={{ alignSelf: msg.role === 'model' ? 'flex-start' : 'flex-end', maxWidth: '80%' }}>
                <div style={{
                  padding: '12px 16px',
                  borderRadius: '12px',
                  background: msg.role === 'model' ? '#FFF' : '#0284C7',
                  color: msg.role === 'model' ? '#0F172A' : '#FFF',
                  boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
                  border: msg.role === 'model' ? '1px solid #E2E8F0' : 'none'
                }}>
                  {msg.text}
                  {msg.imageName && <div style={{ marginTop: 8, fontSize: '12px', opacity: 0.9 }}>📎 {msg.imageName}</div>}
                </div>
              </div>
            ))}
            {loading && (
              <div style={{ alignSelf: 'flex-start', padding: '12px 16px', background: '#FFF', borderRadius: '12px', color: '#64748B', border: '1px solid #E2E8F0' }}>
                {getTranslated('typing')}
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
            <label className="btn btn-secondary" style={{ padding: '0 16px', height: '48px', display: 'flex', alignItems: 'center', cursor: 'pointer' }}>
              {getTranslated('attach')}
              <input type="file" accept="image/*,.pdf" style={{ display: 'none' }} onChange={onFileChange} />
            </label>
            <button className="btn btn-secondary" style={{ padding: '0 16px', height: '48px', background: isListening ? '#FEE2E2' : '#F1F5F9', color: isListening ? '#DC2626' : '#0F172A' }} onClick={toggleListen}>
              {isListening ? getTranslated('listening') : getTranslated('speak')}
            </button>
            <input 
              className="input" 
              style={{ flex: 1, height: '48px' }}
              value={input} 
              onChange={e => setInput(e.target.value)} 
              onKeyDown={e => e.key === 'Enter' && handleSend()}
              placeholder={getTranslated('placeholder')}
              disabled={loading}
            />
            <button className="btn btn-primary" style={{ height: '48px' }} onClick={() => handleSend()} disabled={loading || !input.trim()}>
              {getTranslated('send')}
            </button>
          </div>
        </div>
      ) : (
        <div className="card">
          <h3 style={{ marginBottom: 16 }}>{getTranslated('complete')}</h3>
          <p>{getTranslated('verify')}</p>
          <div className="grid cols-1" style={{ marginTop: 20, gap: 16 }}>
            <div><b>{getTranslated('dept')}</b><br /><StatusTag kind="primary">{summaryData?.department || 'General'}</StatusTag></div>
            <div><b>{getTranslated('chief')}</b><br />{summaryData?.chiefComplaint || 'N/A'}</div>
            <div><b>{getTranslated('priority')}</b><br /><StatusTag kind={summaryData?.priority === 'P1' ? 'danger' : summaryData?.priority === 'P2' ? 'warning' : 'success'}>{summaryData?.priority || 'P3'}</StatusTag></div>
          </div>
          <div style={{ display: 'flex', gap: 10, marginTop: 24 }}>
            <button className="btn btn-secondary" onClick={() => setAssessmentDone(false)}>{getTranslated('modify')}</button>
            <button className="btn btn-primary" onClick={confirmAndProceed}>{getTranslated('confirm')}</button>
          </div>
        </div>
      )}
    </KioskShell>
  );
}
