import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import KioskShell from '../../components/KioskShell';
import { useApp } from '../../context/AppContext';
import { updateQueueToken } from '../../data/queueStore';
import { VoiceBar, StatusTag, speakText } from '../../components/ui';

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

export default function AiAssistant() {
  const { state, patch } = useApp();
  const nav = useNavigate();
  
  const lang = state.language || 'English';
  
  const pName = state.patient?.name || 'Unknown';
  const pAge = state.patient?.age || 'Unknown';
  const pBg = state.patient?.bloodGroup || 'Unknown';

  const SYSTEM_INSTRUCTION = `You are an AI Clinical Intake Assistant for AAROGYAVAANI. 
Your goal is to gather the patient's Chief Complaint, Symptoms, and relevant medical history in a friendly, concise manner.
Ask 1 or 2 questions at most at a time.
IMPORTANT: You MUST communicate with the patient entirely in ${lang}.
Keep your responses short.
CRITICAL FLOW:
1. First, gather Chief complaint, main symptoms, and duration.
2. Once you have this basic information, you MUST ask the patient if they have any previous medical reports, lab results, or prescriptions to upload. When you ask this, you MUST end your message with the exact tag: [ASK_REPORT]
3. Wait for their response (an uploaded image/PDF or them saying they don't have any). If they upload a report, extract the key details (OCR) and factor it into your assessment.
4. After resolving the report step, or if the user asks to fix an error in the summary, you MUST end your message with the exact tag: [ASSESSMENT_COMPLETE]
5. Then, in a new line, provide a detailed JSON summary block wrapped in \`\`\`json 
{ 
  "chiefComplaint": "what customer is feeling",
  "duration": "how long",
  "possibleDisease": "possible disease",
  "department": "Suggested Department / Doctor", 
  "priority": "P3",
  "ocrReport": "Summary of scanned OCR report (if applicable, else 'No report')"
} \`\`\`
Make sure the JSON block is the very last thing. Note the patient's profile: Name: ${pName}, Age: ${pAge}, Blood Group: ${pBg}. Incorporate this into your analysis if necessary.`;

  const getInitialMessage = () => {
    const name = state.patient?.name?.split(' ')[0] || '';
    if (lang === 'हिन्दी') {
      return `नमस्ते ${name}, मैं आपका AI क्लिनिकल असिस्टेंट हूँ। क्या आप संक्षेप में बता सकते हैं कि आज आप अस्पताल क्यों आए हैं?`;
    }
    if (lang === 'ਪੰਜਾਬੀ') {
      return `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ${name}, ਮੈਂ ਤੁਹਾਡਾ AI ਕਲੀਨਿਕਲ ਸਹਾਇਕ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਸੰਖੇਪ ਵਿੱਚ ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਅੱਜ ਹਸਪਤਾਲ ਕਿਉਂ ਆਏ ਹੋ?`;
    }
    return `Hello ${name}, I am your AI clinical assistant. Could you briefly describe what brings you to the hospital today?`;
  };

  const getVoiceBarText = () => {
    if (lang === 'हिन्दी') {
      return assessmentDone ? "कृपया अपने मूल्यांकन सारांश की पुष्टि करें।" : "मैं सुन रहा हूँ। कृपया अपनी स्वास्थ्य संबंधी चिंताओं का वर्णन करें।";
    }
    if (lang === 'ਪੰਜਾਬੀ') {
      return assessmentDone ? "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਮੁਲਾਂਕਣ ਸੰਖੇਪ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।" : "ਮੈਂ ਸੁਣ ਰਿਹਾ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀਆਂ ਸਿਹਤ ਸਮੱਸਿਆਵਾਂ ਦਾ ਵਰਣਨ ਕਰੋ।";
    }
    return assessmentDone ? "Please verify your assessment summary." : "I am listening. Please describe your health concerns.";
  };

  const getTranslated = (key) => {
    const d = {
      stepLabel: { English: 'STEP 2 · AI TRIAGE', 'हिन्दी': 'चरण 2 · AI ट्राइएज', 'ਪੰਜਾਬੀ': 'ਕਦਮ 2 · AI ਟ੍ਰਾਈਏਜ' },
      title: { English: 'AI Clinical Assistant', 'हिन्दी': 'AI क्लिनिकल असिस्टेंट', 'ਪੰਜਾਬੀ': 'AI ਕਲੀਨਿਕਲ ਸਹਾਇਕ' },
      typing: { English: 'AI is typing...', 'हिन्दी': 'AI टाइप कर रहा है...', 'ਪੰਜਾਬੀ': 'AI ਟਾਈਪ ਕਰ ਰਿਹਾ ਹੈ...' },
      attach: { English: '📎 Attach', 'हिन्दी': '📎 फाइल जोड़ें', 'ਪੰਜਾਬੀ': '📎 ਫਾਈਲ ਜੋੜੋ' },
      speak: { English: '🎤 Speak', 'हिन्दी': '🎤 बोलें', 'ਪੰਜਾਬੀ': '🎤 ਬੋਲੋ' },
      listening: { English: '🎙️ Listening...', 'हिन्दी': '🎙️ सुन रहा हूँ...', 'ਪੰਜਾਬੀ': '🎙️ ਸੁਣ ਰਿਹਾ ਹਾਂ...' },
      placeholder: { English: 'Type your symptoms here...', 'हिन्दी': 'अपने लक्षण यहाँ टाइप करें...', 'ਪੰਜਾਬੀ': 'ਆਪਣੇ ਲੱਛਣ ਇੱਥੇ ਟਾਈਪ ਕਰੋ...' },
      send: { English: 'Send', 'हिन्दी': 'भेजें', 'ਪੰਜਾਬੀ': 'ਭੇਜੋ' },
      skip: { English: 'Skip', 'हिन्दी': 'छोड़ें', 'ਪੰਜਾਬੀ': 'ਛੱਡੋ' },
      complete: { English: 'Clinical Assessment Report', 'हिन्दी': 'क्लिनिकल मूल्यांकन रिपोर्ट', 'ਪੰਜਾਬੀ': 'ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ ਰਿਪੋਰਟ' },
      verify: { English: 'Please verify the report generated by the AI before we send it to the doctor.', 'हिन्दी': 'डॉक्टर को भेजने से पहले कृपया AI द्वारा बनाई गई रिपोर्ट की पुष्टि करें।', 'ਪੰਜਾਬੀ': 'ਡਾਕਟਰ ਨੂੰ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਕਿਰਪਾ ਕਰਕੇ AI ਦੁਆਰਾ ਬਣਾਈ ਗਈ ਰਿਪੋਰਟ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।' },
      patientDetails: { English: 'Patient Details', 'हिन्दी': 'मरीज़ का विवरण', 'ਪੰਜਾਬੀ': 'ਮਰੀਜ਼ ਦੇ ਵੇਰਵੇ' },
      dept: { English: 'Suggested Department', 'हिन्दी': 'सुझाया गया विभाग', 'ਪੰਜਾਬੀ': 'ਸੁਝਾਇਆ ਗਿਆ ਵਿਭਾਗ' },
      chief: { English: 'Symptoms / Feeling', 'हिन्दी': 'लक्षण / महसूस होना', 'ਪੰਜਾਬੀ': 'ਲੱਛਣ / ਮਹਿਸੂਸ ਕਰਨਾ' },
      duration: { English: 'Duration', 'हिन्दी': 'अवधि (कब से)', 'ਪੰਜਾਬੀ': 'ਅਵਧੀ (ਕਦੋਂ ਤੋਂ)' },
      disease: { English: 'Possible Disease', 'हिन्दी': 'संभावित बीमारी', 'ਪੰਜਾਬੀ': 'ਸੰਭਾਵਿਤ ਬਿਮਾਰੀ' },
      ocr: { English: 'OCR / Past Reports', 'हिन्दी': 'OCR / पिछली रिपोर्ट', 'ਪੰਜਾਬੀ': 'OCR / ਪਿਛਲੀ ਰਿਪੋਰਟ' },
      priority: { English: 'Priority Assessment', 'हिन्दी': 'प्राथमिकता मूल्यांकन', 'ਪੰਜਾਬੀ': 'ਤਰਜੀਹ ਮੁਲਾਂਕਣ' },
      correctionLabel: { English: 'AI Suggestion / Correct Error', 'हिन्दी': 'AI सुझाव / त्रुटि सुधारें', 'ਪੰਜਾਬੀ': 'AI ਸੁਝਾਅ / ਗਲਤੀ ਠੀਕ ਕਰੋ' },
      correctionPlaceholder: { English: 'Describe what is wrong in the report...', 'हिन्दी': 'रिपोर्ट में क्या गलत है, उसका वर्णन करें...', 'ਪੰਜਾਬੀ': 'ਦੱਸੋ ਕਿ ਰਿਪੋਰਟ ਵਿੱਚ ਕੀ ਗਲਤ ਹੈ...' },
      fixReportBtn: { English: 'Fix & Regenerate', 'हिन्दी': 'सुधारें और फिर से बनाएं', 'ਪੰਜਾਬੀ': 'ਠੀਕ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਬਣਾਓ' },
      download: { English: 'Download Report', 'हिन्दी': 'रिपोर्ट डाउनलोड करें', 'ਪੰਜਾਬੀ': 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ' },
      modify: { English: 'Modify Details', 'हिन्दी': 'विवरण बदलें', 'ਪੰਜਾਬੀ': 'ਵੇਰਵੇ ਬਦਲੋ' },
      confirm: { English: 'Confirm & Send to Doctor', 'हिन्दी': 'पुष्टि करें और डॉक्टर को भेजें', 'ਪੰਜਾਬੀ': 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਡਾਕਟਰ ਨੂੰ ਭੇਜੋ' },
      error: { English: 'Sorry, I encountered an error.', 'हिन्दी': 'क्षमा करें, मुझे एक त्रुटि मिली।', 'ਪੰਜਾਬੀ': 'ਮਾਫ ਕਰਨਾ, ਮੈਨੂੰ ਇੱਕ ਗਲਤੀ ਆਈ।' }
    };
    return d[key][state.language] || d[key]['English'];
  };

  const [messages, setMessages] = useState([
    { role: 'model', text: getInitialMessage() }
  ]);
  const [input, setInput] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [loading, setLoading] = useState(false);
  const [assessmentDone, setAssessmentDone] = useState(false);
  const [summaryData, setSummaryData] = useState(null);
  const [correctionInput, setCorrectionInput] = useState('');
  
  const chatEndRef = useRef(null);

  // Auto-speak initial message once on mount and when language changes (if no interaction yet)
  useEffect(() => {
    if (messages.length === 1) {
      const msg = getInitialMessage();
      setMessages([{ role: 'model', text: msg }]);
      
      let langCode = 'en-US';
      if (lang === 'हिन्दी') langCode = 'hi-IN';
      else if (lang === 'ਪੰਜਾਬੀ') langCode = 'pa-IN';
      
      // Add a slight delay so it doesn't overlap with the KioskShell language change confirmation
      setTimeout(() => {
        speakText(msg, langCode);
      }, 1000);
    }
  }, [lang]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const toggleListen = () => {
    if (isListening) return; // Speech recognition will auto-stop
    
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Voice recognition is not supported in this browser.");
      return;
    }
    const recognition = new SpeechRecognition();
    if (lang === 'हिन्दी') recognition.lang = 'hi-IN';
    else if (lang === 'ਪੰਜਾਬੀ') recognition.lang = 'pa-IN';
    else recognition.lang = 'en-US';
    recognition.interimResults = false;
    
    recognition.onstart = () => setIsListening(true);
    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;
      setInput(prev => prev + ' ' + transcript);
    };
    recognition.onerror = (event) => {
      console.error(event.error);
      setIsListening(false);
    };
    recognition.onend = () => setIsListening(false);
    
    recognition.start();
  };

  const [isCorrectionListening, setIsCorrectionListening] = useState(false);
  const toggleCorrectionListen = () => {
    if (isCorrectionListening) return;
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) return;
    const recognition = new SpeechRecognition();
    recognition.lang = lang === 'हिन्दी' ? 'hi-IN' : lang === 'ਪੰਜਾਬੀ' ? 'pa-IN' : 'en-US';
    recognition.interimResults = false;
    setIsCorrectionListening(true);
    recognition.onresult = (event) => setCorrectionInput(prev => prev + ' ' + event.results[0][0].transcript);
    recognition.onerror = () => setIsCorrectionListening(false);
    recognition.onend = () => setIsCorrectionListening(false);
    recognition.start();
  };

  const handleSend = async (imageFile = null, overrideText = null) => {
    if (!input.trim() && !imageFile && !overrideText) return;
    
    const userText = overrideText || input.trim();
    setInput('');
    
    const newMsg = { role: 'user', text: userText };
    let inlineData = null;
    
    if (imageFile) {
      newMsg.imageName = imageFile.name;
      const reader = new FileReader();
      const base64Promise = new Promise((resolve) => {
        reader.onload = (e) => {
          const b64 = e.target.result.split(',')[1];
          resolve({ mimeType: imageFile.type, data: b64 });
        };
      });
      reader.readAsDataURL(imageFile);
      inlineData = await base64Promise;
      newMsg.text = newMsg.text || 'Uploaded a file.';
    }
    
    const updatedMessages = [...messages, newMsg];
    setMessages(updatedMessages);
    setLoading(true);

    try {
      const rawContents = updatedMessages
        .filter((m, i) => !(i === 0 && m.role === 'model'))
        .filter(m => !m.text.includes('Network error') && !m.text.includes('त्रुटि') && !m.text.includes('ਗਲਤੀ'))
        .map(m => {
          const parts = [{ text: m.text }];
          if (m.role === 'user' && inlineData && m === newMsg) {
            parts.push({ inlineData });
          }
          return { role: m.role === 'model' ? 'model' : 'user', parts };
        });

      const contents = [];
      for (const msg of rawContents) {
        if (contents.length > 0 && contents[contents.length - 1].role === msg.role) {
          contents[contents.length - 1].parts.push({ text: '\n\n' }, ...msg.parts);
        } else {
          contents.push(msg);
        }
      }

      const response = await fetch(GEMINI_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: SYSTEM_INSTRUCTION }] },
          contents
        })
      });

      const data = await response.json();
      if (!response.ok) {
        console.error("Gemini API Error:", data);
        throw new Error(data.error?.message || 'API Error');
      }

      const botText = data.candidates?.[0]?.content?.parts?.[0]?.text || getTranslated('error');
      
      let cleanText = botText;
      let askReport = false;
      
      if (cleanText.includes('[ASK_REPORT]')) {
        cleanText = cleanText.replace('[ASK_REPORT]', '').trim();
        askReport = true;
      }
      
      if (botText.includes('[ASSESSMENT_COMPLETE]')) {
        cleanText = botText.split('[ASSESSMENT_COMPLETE]')[0].replace('[ASK_REPORT]', '').trim();
        const jsonMatch = botText.match(/```json([\s\S]*?)```/);
        if (jsonMatch) {
          try {
            const parsed = JSON.parse(jsonMatch[1]);
            setSummaryData(parsed);
          } catch (e) {
            setSummaryData({ chiefComplaint: 'Needs review', department: 'General Medicine', priority: 'P3' });
          }
        }
        setAssessmentDone(true);
      }

      setMessages(prev => [...prev, { role: 'model', text: cleanText, askReport }]);
      
      // Auto-speak the AI's response
      let langCode = 'en-US';
      if (lang === 'हिन्दी') langCode = 'hi-IN';
      else if (lang === 'ਪੰਜਾਬੀ') langCode = 'pa-IN';
      speakText(cleanText, langCode);
      
    } catch (error) {
      console.error(error);
      setMessages(prev => [...prev, { role: 'model', text: getTranslated('error') }]);
    } finally {
      setLoading(false);
    }
  };

  const onFileChange = (e) => {
    const file = e.target.files[0];
    if (file) handleSend(file);
    e.target.value = null;
  };

  const confirmAndProceed = () => {
    if (summaryData) {
      const { chiefComplaint, department, priority, duration, possibleDisease, ocrReport } = summaryData;
      patch({
        department: { name: department || 'General Medicine' },
        chiefComplaint: chiefComplaint || 'Details gathered via AI',
      });
      
      const tokenNo = state.token?.tokenNo;
      if (tokenNo) {
        updateQueueToken(tokenNo, {
          department: department || 'General Medicine',
          chiefComplaint: chiefComplaint || 'Details gathered via AI',
          priority: priority || 'P3',
          duration: duration || '',
          possibleDisease: possibleDisease || '',
          ocrReport: ocrReport || ''
        });
      }
    }
    nav('/checkin/token');
  };

  return (
    <KioskShell stepLabel={getTranslated('stepLabel')} title={getTranslated('title')} back="/checkin/patient-dashboard" progress={55} hideNav isListening={isListening}>
      <VoiceBar text={getVoiceBarText()} />
      
      {!assessmentDone ? (
        <div style={{ display: 'flex', flexDirection: 'column', height: '55vh' }}>
          <div style={{ flex: 1, overflowY: 'auto', padding: '16px', background: '#F8FAFC', borderRadius: '8px', marginBottom: '16px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {messages.map((msg, i) => (
              <div key={i} style={{ alignSelf: msg.role === 'model' ? 'flex-start' : 'flex-end', maxWidth: '80%' }}>
                <div style={{
                  padding: '12px 16px',
                  borderRadius: '12px',
                  background: msg.role === 'model' ? '#FFF' : '#0284C7',
                  color: msg.role === 'model' ? '#0F172A' : '#FFF',
                  boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
                  border: msg.role === 'model' ? '1px solid #E2E8F0' : 'none'
                }}>
                  {msg.text}
                  {msg.imageName && <div style={{ marginTop: 8, fontSize: '12px', opacity: 0.9 }}>📎 {msg.imageName}</div>}
                  {msg.role === 'model' && msg.askReport && i === messages.length - 1 && !loading && (
                    <div style={{ marginTop: 12, display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <label className="btn btn-primary btn-sm" style={{ display: 'flex', alignItems: 'center', cursor: 'pointer' }} title="Upload previous reports or lab results">
                        {getTranslated('attach')}
                        <input type="file" accept="image/*,.pdf" style={{ display: 'none' }} onChange={onFileChange} />
                      </label>
                      <button className="btn btn-secondary btn-sm" onClick={() => handleSend(null, "I don't have any previous reports to upload.")} disabled={loading}>
                        {getTranslated('skip')}
                      </button>
                    </div>
                  )}
                </div>
              </div>
            ))}
            {loading && (
              <div style={{ alignSelf: 'flex-start', padding: '12px 16px', background: '#FFF', borderRadius: '12px', color: '#64748B', border: '1px solid #E2E8F0' }}>
                {getTranslated('typing')}
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
            <button className="btn btn-secondary" style={{ padding: '0 16px', height: '48px', background: isListening ? '#FEE2E2' : '#F1F5F9', color: isListening ? '#DC2626' : '#0F172A' }} onClick={toggleListen}>
              {isListening ? getTranslated('listening') : getTranslated('speak')}
            </button>
            <input 
              className="input" 
              style={{ flex: 1, height: '48px' }}
              value={input} 
              onChange={e => setInput(e.target.value)} 
              onKeyDown={e => e.key === 'Enter' && handleSend()}
              placeholder={getTranslated('placeholder')}
              disabled={loading}
            />
            <button className="btn btn-primary" style={{ height: '48px' }} onClick={() => handleSend()} disabled={loading || !input.trim()}>
              {getTranslated('send')}
            </button>
          </div>
        </div>
      ) : (
        <div className="card">
          <h3 style={{ marginBottom: 16 }}>{getTranslated('complete')}</h3>
          <p className="muted small">{getTranslated('verify')}</p>
          <div style={{ background: '#F8FAFC', padding: 16, borderRadius: 8, border: '1px solid #E2E8F0', marginTop: 12 }}>
            <h4 style={{ margin: '0 0 12px 0', borderBottom: '1px solid #CBD5E1', paddingBottom: 8 }}>{getTranslated('patientDetails')}</h4>
            <div className="grid cols-3" style={{ gap: 8, fontSize: 14 }}>
              <div><b>Name:</b> {pName}</div>
              <div><b>Age:</b> {pAge}</div>
              <div><b>Blood Grp:</b> {pBg}</div>
            </div>

            <div className="grid cols-1" style={{ marginTop: 16, gap: 12, fontSize: 14 }}>
              <div><b>{getTranslated('disease')}</b><br />{summaryData?.possibleDisease || 'N/A'}</div>
              <div><b>{getTranslated('chief')}</b><br />{summaryData?.chiefComplaint || 'N/A'}</div>
              <div><b>{getTranslated('duration')}</b><br />{summaryData?.duration || 'N/A'}</div>
              <div><b>{getTranslated('ocr')}</b><br />{summaryData?.ocrReport || 'N/A'}</div>
              <div><b>{getTranslated('dept')}</b><br /><StatusTag kind="primary">{summaryData?.department || 'General'}</StatusTag></div>
              <div><b>{getTranslated('priority')}</b><br /><StatusTag kind={summaryData?.priority === 'P1' ? 'danger' : summaryData?.priority === 'P2' ? 'warning' : 'success'}>{summaryData?.priority || 'P3'}</StatusTag></div>
            </div>
          </div>

          <div style={{ marginTop: 20, padding: '12px', border: '1px solid #E2E8F0', borderRadius: 8, background: '#FFF' }}>
            <label style={{ fontSize: 13, fontWeight: 600, color: '#475569', marginBottom: 8, display: 'block' }}>{getTranslated('correctionLabel')}</label>
            <div style={{ display: 'flex', gap: 8 }}>
              <button 
                className="btn btn-secondary btn-sm" 
                style={{ background: isCorrectionListening ? '#FEE2E2' : '#F1F5F9', color: isCorrectionListening ? '#DC2626' : '#0F172A' }} 
                onClick={toggleCorrectionListen}
              >
                {isCorrectionListening ? getTranslated('listening') : getTranslated('speak')}
              </button>
              <input 
                className="input" 
                style={{ flex: 1 }} 
                value={correctionInput} 
                onChange={e => setCorrectionInput(e.target.value)} 
                placeholder={getTranslated('correctionPlaceholder')} 
              />
              <button 
                className="btn btn-secondary btn-sm" 
                onClick={() => {
                  if(!correctionInput.trim()) return;
                  setAssessmentDone(false);
                  handleSend(null, "There is an error in the report: " + correctionInput + ". Please fix it and regenerate the summary.");
                  setCorrectionInput('');
                }}
              >
                {getTranslated('fixReportBtn')}
              </button>
            </div>
          </div>

          <div style={{ display: 'flex', gap: 10, marginTop: 24, flexWrap: 'wrap' }}>
            <button className="btn btn-secondary" onClick={() => {
              const text = `AAROGYAVAANI CLINICAL REPORT\n\nName: ${pName}\nAge: ${pAge}\nBlood Grp: ${pBg}\n\nDisease: ${summaryData?.possibleDisease}\nSymptoms: ${summaryData?.chiefComplaint}\nDuration: ${summaryData?.duration}\nDepartment: ${summaryData?.department}\nPriority: ${summaryData?.priority}\nOCR/Reports: ${summaryData?.ocrReport}`;
              const blob = new Blob([text], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `Report_${state.patient?.uhid || 'Unknown'}.txt`;
              a.click();
              URL.revokeObjectURL(url);
            }}>{getTranslated('download')}</button>
            <button className="btn btn-primary" onClick={confirmAndProceed} style={{ marginLeft: 'auto' }}>{getTranslated('confirm')}</button>
          </div>
        </div>
      )}
    </KioskShell>
  );
}
